// This file is generated by scripts/sync-starred-repositories.mjs.
// Do not edit manually.

export type GeneratedProject = {
  name: string;
  displayName: string;
  stack: string;
  displayStack: string;
  link: string;
  linkLabel: string;
  blurb: string;
  outcome: string;
  displayOutcome: string;
  challenge: string;
  bullets: string[];
  skills: string[];
};

export const generatedProjects: GeneratedProject[] = [
  {
    "name": "ArkaPrabhaChowdhury/verity",
    "displayName": "Verity",
    "stack": "Python, TypeScript, CSS, Dockerfile, Shell, Ai Agents, Autonomous Agents, Go, Llm, Next.js, Research Agent, Searxng",
    "displayStack": "Python · TypeScript · CSS · Dockerfile · Shell · Ai Agents · Autonomous Agents · Go · Llm · Next.js · Research Agent · Searxng",
    "link": "https://github.com/ArkaPrabhaChowdhury/verity",
    "linkLabel": "ArkaPrabhaChowdhury/verity",
    "blurb": "Evidence-first autonomous research agent with inspectable orchestration, live citations, and reproducible evaluation",
    "outcome": "Evidence-first autonomous research agent with inspectable orchestration, live citations, and reproducible evaluation",
    "displayOutcome": "Evidence-first autonomous research agent with inspectable orchestration, live citations, and reproducible evaluation",
    "challenge": "Evidence-first autonomous research agent with inspectable orchestration, live citations, and reproducible evaluation",
    "bullets": [
      "Starred on GitHub · Primary language: Python.",
      "Topics: ai-agents, autonomous-agents, golang, llm, nextjs, research-agent, searxng."
    ],
    "skills": [
      "Python",
      "TypeScript",
      "CSS",
      "Dockerfile",
      "Shell",
      "Ai Agents",
      "Autonomous Agents",
      "Go",
      "Llm",
      "Next.js",
      "Research Agent",
      "Searxng"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/leetcode-flow-lab",
    "displayName": "Leetcode Flow Lab",
    "stack": "JavaScript, CSS, Python, HTML",
    "displayStack": "JavaScript · CSS · Python · HTML",
    "link": "https://github.com/ArkaPrabhaChowdhury/leetcode-flow-lab",
    "linkLabel": "ArkaPrabhaChowdhury/leetcode-flow-lab",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: JavaScript."
    ],
    "skills": [
      "JavaScript",
      "CSS",
      "Python",
      "HTML"
    ]
  }
];

export const starredSkills: string[] = [
  "Ai Agents",
  "Autonomous Agents",
  "CSS",
  "Dockerfile",
  "Go",
  "HTML",
  "JavaScript",
  "Llm",
  "Next.js",
  "Python",
  "Research Agent",
  "Searxng",
  "Shell",
  "TypeScript"
];
