// This file is generated by scripts/sync-starred-repositories.mjs.
// Do not edit manually.

export type GeneratedProject = {
  name: string;
  displayName: string;
  stack: string;
  displayStack: string;
  link: string;
  linkLabel: string;
  blurb: string;
  outcome: string;
  displayOutcome: string;
  challenge: string;
  bullets: string[];
  skills: string[];
};

export const generatedProjects: GeneratedProject[] = [
  {
    "name": "Graphify-Labs/graphify",
    "displayName": "Graphify",
    "stack": "Python, Dockerfile, Ai Agents, Antigravity, Ast, Claude Code, Code Analysis, Code Search, Codex, Cursor, Developer Tools, Gemini, Graphrag, Knowledge Graph, Leiden, Llm, Mcp, Openclaw, Rag, Skills, Tree Sitter",
    "displayStack": "Python · Dockerfile · Ai Agents · Antigravity · Ast · Claude Code · Code Analysis · Code Search · Codex · Cursor · Developer Tools · Gemini · Graphrag · Knowledge Graph · Leiden · Llm · Mcp · Openclaw · Rag · Skills · Tree Sitter",
    "link": "https://github.com/Graphify-Labs/graphify",
    "linkLabel": "Graphify-Labs/graphify",
    "blurb": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "outcome": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "displayOutcome": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "challenge": "Turn any codebase, with its docs, SQL schemas, configs, and PDFs, into a queryable knowledge graph. A /graphify skill for Claude Code, Cursor, Codex, and Gemini CLI: local deterministic AST parsing, every edge explained, no vector store.",
    "bullets": [
      "Starred on GitHub · Primary language: Python.",
      "Topics: ai-agents, antigravity, ast, claude-code, code-analysis, code-search, codex, cursor, developer-tools, gemini, graphrag, knowledge-graph, leiden, llm, mcp, openclaw, rag, skills, tree-sitter."
    ],
    "skills": [
      "Python",
      "Dockerfile",
      "Ai Agents",
      "Antigravity",
      "Ast",
      "Claude Code",
      "Code Analysis",
      "Code Search",
      "Codex",
      "Cursor",
      "Developer Tools",
      "Gemini",
      "Graphrag",
      "Knowledge Graph",
      "Leiden",
      "Llm",
      "Mcp",
      "Openclaw",
      "Rag",
      "Skills",
      "Tree Sitter"
    ]
  },
  {
    "name": "slopus/happy",
    "displayName": "Happy",
    "stack": "TypeScript, JavaScript, CSS, Python, Shell, HTML, Dockerfile, PLpgSQL, Rust, Go, Claude Code, Claude Desktop, Claude Mobile, Codex, Codex Cli, Hacktoberfest",
    "displayStack": "TypeScript · JavaScript · CSS · Python · Shell · HTML · Dockerfile · PLpgSQL · Rust · Go · Claude Code · Claude Desktop · Claude Mobile · Codex · Codex Cli · Hacktoberfest",
    "link": "https://github.com/slopus/happy",
    "linkLabel": "slopus/happy",
    "blurb": "Mobile and Web client for Codex and Claude Code, with realtime voice, encryption and fully featured",
    "outcome": "Mobile and Web client for Codex and Claude Code, with realtime voice, encryption and fully featured",
    "displayOutcome": "Mobile and Web client for Codex and Claude Code, with realtime voice, encryption and fully featured",
    "challenge": "Mobile and Web client for Codex and Claude Code, with realtime voice, encryption and fully featured",
    "bullets": [
      "Starred on GitHub · Primary language: TypeScript.",
      "Topics: claude-code, claude-desktop, claude-mobile, codex, codex-cli, hacktoberfest."
    ],
    "skills": [
      "TypeScript",
      "JavaScript",
      "CSS",
      "Python",
      "Shell",
      "HTML",
      "Dockerfile",
      "PLpgSQL",
      "Rust",
      "Go",
      "Claude Code",
      "Claude Desktop",
      "Claude Mobile",
      "Codex",
      "Codex Cli",
      "Hacktoberfest"
    ]
  },
  {
    "name": "BipulRaman/AppNest",
    "displayName": "AppNest",
    "stack": "Rust, JavaScript, CSS, HTML, Axum, Developer Tools, Localhost, Process Manager",
    "displayStack": "Rust · JavaScript · CSS · HTML · Axum · Developer Tools · Localhost · Process Manager",
    "link": "https://github.com/BipulRaman/AppNest",
    "linkLabel": "BipulRaman/AppNest",
    "blurb": "Lightweight local app manager for developers. Build, run, monitor — all from one dashboard. 5 MB, zero dependencies, built with Rust.",
    "outcome": "Lightweight local app manager for developers. Build, run, monitor — all from one dashboard. 5 MB, zero dependencies, built with Rust.",
    "displayOutcome": "Lightweight local app manager for developers. Build, run, monitor — all from one dashboard. 5 MB, zero dependencies, built with Rust.",
    "challenge": "Lightweight local app manager for developers. Build, run, monitor — all from one dashboard. 5 MB, zero dependencies, built with Rust.",
    "bullets": [
      "Starred on GitHub · Primary language: Rust.",
      "Topics: axum, developer-tools, localhost, process-manager, rust."
    ],
    "skills": [
      "Rust",
      "JavaScript",
      "CSS",
      "HTML",
      "Axum",
      "Developer Tools",
      "Localhost",
      "Process Manager"
    ]
  },
  {
    "name": "akash-aman/dynamix-layout",
    "displayName": "Dynamix Layout",
    "stack": "TypeScript, CSS, JavaScript, HTML, Drag And Drop, Frontend, Layout Engine, Resizable Panels, Ui Components, Ui Engineering, Ux Design",
    "displayStack": "TypeScript · CSS · JavaScript · HTML · Drag And Drop · Frontend · Layout Engine · Resizable Panels · Ui Components · Ui Engineering · Ux Design",
    "link": "https://github.com/akash-aman/dynamix-layout",
    "linkLabel": "akash-aman/dynamix-layout",
    "blurb": "🚀 JavaScript package 📦  for creating dynamic layouts 🪟 with ease 💤.",
    "outcome": "🚀 JavaScript package 📦  for creating dynamic layouts 🪟 with ease 💤.",
    "displayOutcome": "🚀 JavaScript package 📦  for creating dynamic layouts 🪟 with ease 💤.",
    "challenge": "🚀 JavaScript package 📦  for creating dynamic layouts 🪟 with ease 💤.",
    "bullets": [
      "Starred on GitHub · Primary language: TypeScript.",
      "Topics: drag-and-drop, frontend, layout-engine, resizable-panels, ts, ui-components, ui-engineering, ux-design."
    ],
    "skills": [
      "TypeScript",
      "CSS",
      "JavaScript",
      "HTML",
      "Drag And Drop",
      "Frontend",
      "Layout Engine",
      "Resizable Panels",
      "Ui Components",
      "Ui Engineering",
      "Ux Design"
    ]
  },
  {
    "name": "GouravNainwaya/ScopeXFintech",
    "displayName": "ScopeXFintech",
    "stack": "JavaScript",
    "displayStack": "JavaScript",
    "link": "https://github.com/GouravNainwaya/ScopeXFintech",
    "linkLabel": "GouravNainwaya/ScopeXFintech",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: JavaScript."
    ],
    "skills": [
      "JavaScript"
    ]
  },
  {
    "name": "TaherSanwar2000/ScopeX",
    "displayName": "ScopeX",
    "stack": "Java, TypeScript, JavaScript",
    "displayStack": "Java · TypeScript · JavaScript",
    "link": "https://github.com/TaherSanwar2000/ScopeX",
    "linkLabel": "TaherSanwar2000/ScopeX",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: Java."
    ],
    "skills": [
      "Java",
      "TypeScript",
      "JavaScript"
    ]
  },
  {
    "name": "shiv-thacker/Remittance-Transfer-App",
    "displayName": "Remittance Transfer App",
    "stack": "GitHub project",
    "displayStack": "GitHub project",
    "link": "https://github.com/shiv-thacker/Remittance-Transfer-App",
    "linkLabel": "shiv-thacker/Remittance-Transfer-App",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub."
    ],
    "skills": []
  },
  {
    "name": "Pythagora-io/gpt-pilot",
    "displayName": "Gpt Pilot",
    "stack": "Python, TypeScript, JavaScript, Smarty, CSS, Shell, EJS, Dockerfile, HTML, Go Template, Mako, Ai, Codegen, Coding Assistant, Developer Tools, Gpt 4, Research Project",
    "displayStack": "Python · TypeScript · JavaScript · Smarty · CSS · Shell · EJS · Dockerfile · HTML · Go Template · Mako · Ai · Codegen · Coding Assistant · Developer Tools · Gpt 4 · Research Project",
    "link": "https://github.com/Pythagora-io/gpt-pilot",
    "linkLabel": "Pythagora-io/gpt-pilot",
    "blurb": "The first real AI developer",
    "outcome": "The first real AI developer",
    "displayOutcome": "The first real AI developer",
    "challenge": "The first real AI developer",
    "bullets": [
      "Starred on GitHub · Primary language: Python.",
      "Topics: ai, codegen, coding-assistant, developer-tools, gpt-4, research-project."
    ],
    "skills": [
      "Python",
      "TypeScript",
      "JavaScript",
      "Smarty",
      "CSS",
      "Shell",
      "EJS",
      "Dockerfile",
      "HTML",
      "Go Template",
      "Mako",
      "Ai",
      "Codegen",
      "Coding Assistant",
      "Developer Tools",
      "Gpt 4",
      "Research Project"
    ]
  },
  {
    "name": "Ruffy45/PortfolioNeww",
    "displayName": "PortfolioNeww",
    "stack": "JavaScript, CSS, HTML",
    "displayStack": "JavaScript · CSS · HTML",
    "link": "https://github.com/Ruffy45/PortfolioNeww",
    "linkLabel": "Ruffy45/PortfolioNeww",
    "blurb": "wohooo new portfolio",
    "outcome": "wohooo new portfolio",
    "displayOutcome": "wohooo new portfolio",
    "challenge": "wohooo new portfolio",
    "bullets": [
      "Starred on GitHub · Primary language: JavaScript."
    ],
    "skills": [
      "JavaScript",
      "CSS",
      "HTML"
    ]
  },
  {
    "name": "glific/mobile",
    "displayName": "Mobile",
    "stack": "TypeScript, JavaScript",
    "displayStack": "TypeScript · JavaScript",
    "link": "https://github.com/glific/mobile",
    "linkLabel": "glific/mobile",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: TypeScript."
    ],
    "skills": [
      "TypeScript",
      "JavaScript"
    ]
  },
  {
    "name": "vasturiano/react-globe.gl",
    "displayName": "React Globe.Gl",
    "stack": "HTML, JavaScript, Datavisualization, Globe, React, Threejs, Webgl",
    "displayStack": "HTML · JavaScript · Datavisualization · Globe · React · Threejs · Webgl",
    "link": "https://github.com/vasturiano/react-globe.gl",
    "linkLabel": "vasturiano/react-globe.gl",
    "blurb": "React component for Globe Data Visualization using ThreeJS/WebGL",
    "outcome": "React component for Globe Data Visualization using ThreeJS/WebGL",
    "displayOutcome": "React component for Globe Data Visualization using ThreeJS/WebGL",
    "challenge": "React component for Globe Data Visualization using ThreeJS/WebGL",
    "bullets": [
      "Starred on GitHub · Primary language: HTML.",
      "Topics: datavisualization, globe, react, threejs, webgl."
    ],
    "skills": [
      "HTML",
      "JavaScript",
      "Datavisualization",
      "Globe",
      "React",
      "Threejs",
      "Webgl"
    ]
  },
  {
    "name": "rahuldkjain/github-profile-readme-generator",
    "displayName": "Github Profile Readme Generator",
    "stack": "TypeScript, CSS, JavaScript, Shell, Gatsby, Generator, Github, Hacktoberfest, Markdown, React, Readme",
    "displayStack": "TypeScript · CSS · JavaScript · Shell · Gatsby · Generator · Github · Hacktoberfest · Markdown · React · Readme",
    "link": "https://github.com/rahuldkjain/github-profile-readme-generator",
    "linkLabel": "rahuldkjain/github-profile-readme-generator",
    "blurb": "🚀 Generate GitHub profile README easily with the latest add-ons like visitors count, GitHub stats, etc using minimal UI.",
    "outcome": "🚀 Generate GitHub profile README easily with the latest add-ons like visitors count, GitHub stats, etc using minimal UI.",
    "displayOutcome": "🚀 Generate GitHub profile README easily with the latest add-ons like visitors count, GitHub stats, etc using minimal UI.",
    "challenge": "🚀 Generate GitHub profile README easily with the latest add-ons like visitors count, GitHub stats, etc using minimal UI.",
    "bullets": [
      "Starred on GitHub · Primary language: TypeScript.",
      "Topics: gatsby, generator, github, hacktoberfest, markdown, react, readme."
    ],
    "skills": [
      "TypeScript",
      "CSS",
      "JavaScript",
      "Shell",
      "Gatsby",
      "Generator",
      "Github",
      "Hacktoberfest",
      "Markdown",
      "React",
      "Readme"
    ]
  },
  {
    "name": "WeMakeDevs/wemakedevs-archive",
    "displayName": "Wemakedevs Archive",
    "stack": "JavaScript, CSS, HTML, Dockerfile, Shell, Community, Hacktoberfest, React",
    "displayStack": "JavaScript · CSS · HTML · Dockerfile · Shell · Community · Hacktoberfest · React",
    "link": "https://github.com/WeMakeDevs/wemakedevs-archive",
    "linkLabel": "WeMakeDevs/wemakedevs-archive",
    "blurb": "Inspire. Educate. Empower.",
    "outcome": "Inspire. Educate. Empower.",
    "displayOutcome": "Inspire. Educate. Empower.",
    "challenge": "Inspire. Educate. Empower.",
    "bullets": [
      "Starred on GitHub · Primary language: JavaScript.",
      "Topics: community, hacktoberfest, react."
    ],
    "skills": [
      "JavaScript",
      "CSS",
      "HTML",
      "Dockerfile",
      "Shell",
      "Community",
      "Hacktoberfest",
      "React"
    ]
  },
  {
    "name": "permitio/opal",
    "displayName": "Opal",
    "stack": "Python, Shell, Dockerfile, Makefile, Open Policy Agent, Authorization, Cedar, Hacktoberfest, Microservices, Opa, Opal, Openfga, Policy, Policy As Code, Pubsub, Realtime, Websocket",
    "displayStack": "Python · Shell · Dockerfile · Makefile · Open Policy Agent · Authorization · Cedar · Hacktoberfest · Microservices · Opa · Opal · Openfga · Policy · Policy As Code · Pubsub · Realtime · Websocket",
    "link": "https://github.com/permitio/opal",
    "linkLabel": "permitio/opal",
    "blurb": "Policy and data administration, distribution, and real-time updates on top of Policy Agents (OPA, Cedar, ...)",
    "outcome": "Policy and data administration, distribution, and real-time updates on top of Policy Agents (OPA, Cedar, ...)",
    "displayOutcome": "Policy and data administration, distribution, and real-time updates on top of Policy Agents (OPA, Cedar, ...)",
    "challenge": "Policy and data administration, distribution, and real-time updates on top of Policy Agents (OPA, Cedar, ...)",
    "bullets": [
      "Starred on GitHub · Primary language: Python.",
      "Topics: authorization, cedar, hacktoberfest, microservices, opa, opal, open-policy-agent, openfga, policy, policy-as-code, pubsub, realtime, websocket."
    ],
    "skills": [
      "Python",
      "Shell",
      "Dockerfile",
      "Makefile",
      "Open Policy Agent",
      "Authorization",
      "Cedar",
      "Hacktoberfest",
      "Microservices",
      "Opa",
      "Opal",
      "Openfga",
      "Policy",
      "Policy As Code",
      "Pubsub",
      "Realtime",
      "Websocket"
    ]
  },
  {
    "name": "biratdatta/Webpage-Maker",
    "displayName": "Webpage Maker",
    "stack": "HTML, CSS, JavaScript, TypeScript, Python, SCSS, PHP, Shell, Github, Hacktoberfest, Hacktoberfest2022, Learn, Student Vscode",
    "displayStack": "HTML · CSS · JavaScript · TypeScript · Python · SCSS · PHP · Shell · Github · Hacktoberfest · Hacktoberfest2022 · Learn · Student Vscode",
    "link": "https://github.com/biratdatta/Webpage-Maker",
    "linkLabel": "biratdatta/Webpage-Maker",
    "blurb": "Cheat sheet for HTML and CSS",
    "outcome": "Cheat sheet for HTML and CSS",
    "displayOutcome": "Cheat sheet for HTML and CSS",
    "challenge": "Cheat sheet for HTML and CSS",
    "bullets": [
      "Starred on GitHub · Primary language: HTML.",
      "Topics: github, hacktoberfest, hacktoberfest2022, learn, student-vscode."
    ],
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Python",
      "SCSS",
      "PHP",
      "Shell",
      "Github",
      "Hacktoberfest",
      "Hacktoberfest2022",
      "Learn",
      "Student Vscode"
    ]
  },
  {
    "name": "csdojo-defaang/defaang",
    "displayName": "Defaang",
    "stack": "TypeScript, PLpgSQL, JavaScript, CSS, Shell, Hacktoberfest, Hacktoberfest Accepted, Hacktoberfest2022, Next.js, Supabase, Tailwind CSS",
    "displayStack": "TypeScript · PLpgSQL · JavaScript · CSS · Shell · Hacktoberfest · Hacktoberfest Accepted · Hacktoberfest2022 · Next.js · Supabase · Tailwind CSS",
    "link": "https://github.com/csdojo-defaang/defaang",
    "linkLabel": "csdojo-defaang/defaang",
    "blurb": "A website that will curate recently-asked interview questions from FAANG+. Currently inactive. Check out: https://github.com/ykdojo/OpenStream",
    "outcome": "A website that will curate recently-asked interview questions from FAANG+. Currently inactive. Check out: https://github.com/ykdojo/OpenStream",
    "displayOutcome": "A website that will curate recently-asked interview questions from FAANG+. Currently inactive. Check out: https://github.com/ykdojo/OpenStream",
    "challenge": "A website that will curate recently-asked interview questions from FAANG+. Currently inactive. Check out: https://github.com/ykdojo/OpenStream",
    "bullets": [
      "Starred on GitHub · Primary language: TypeScript.",
      "Topics: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, nextjs, supabase, tailwindcss."
    ],
    "skills": [
      "TypeScript",
      "PLpgSQL",
      "JavaScript",
      "CSS",
      "Shell",
      "Hacktoberfest",
      "Hacktoberfest Accepted",
      "Hacktoberfest2022",
      "Next.js",
      "Supabase",
      "Tailwind CSS"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/Unigrade",
    "displayName": "Unigrade",
    "stack": "HTML, CSS, JavaScript, Bootstrap5, Css3",
    "displayStack": "HTML · CSS · JavaScript · Bootstrap5 · Css3",
    "link": "https://github.com/ArkaPrabhaChowdhury/Unigrade",
    "linkLabel": "ArkaPrabhaChowdhury/Unigrade",
    "blurb": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "outcome": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "displayOutcome": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "challenge": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "bullets": [
      "Starred on GitHub · Primary language: HTML.",
      "Topics: bootstrap5, css3."
    ],
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap5",
      "Css3"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/Diabetes_Prediction",
    "displayName": "Diabetes Prediction",
    "stack": "Jupyter Notebook",
    "displayStack": "Jupyter Notebook",
    "link": "https://github.com/ArkaPrabhaChowdhury/Diabetes_Prediction",
    "linkLabel": "ArkaPrabhaChowdhury/Diabetes_Prediction",
    "blurb": "Optimal Classification Algorithm for predicting diabetes",
    "outcome": "Optimal Classification Algorithm for predicting diabetes",
    "displayOutcome": "Optimal Classification Algorithm for predicting diabetes",
    "challenge": "Optimal Classification Algorithm for predicting diabetes",
    "bullets": [
      "Starred on GitHub · Primary language: Jupyter Notebook."
    ],
    "skills": [
      "Jupyter Notebook"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/ChatbotAPP",
    "displayName": "ChatbotAPP",
    "stack": "Java",
    "displayStack": "Java",
    "link": "https://github.com/ArkaPrabhaChowdhury/ChatbotAPP",
    "linkLabel": "ArkaPrabhaChowdhury/ChatbotAPP",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: Java."
    ],
    "skills": [
      "Java"
    ]
  },
  {
    "name": "bikashthapa01/firebase-authentication-android",
    "displayName": "Firebase Authentication Android",
    "stack": "Java",
    "displayStack": "Java",
    "link": "https://github.com/bikashthapa01/firebase-authentication-android",
    "linkLabel": "bikashthapa01/firebase-authentication-android",
    "blurb": "A Simple Android Studio Projects that implements login and registration system using google firebase.",
    "outcome": "A Simple Android Studio Projects that implements login and registration system using google firebase.",
    "displayOutcome": "A Simple Android Studio Projects that implements login and registration system using google firebase.",
    "challenge": "A Simple Android Studio Projects that implements login and registration system using google firebase.",
    "bullets": [
      "Starred on GitHub · Primary language: Java."
    ],
    "skills": [
      "Java"
    ]
  },
  {
    "name": "benedekrozemberczki/awesome-decision-tree-papers",
    "displayName": "Awesome Decision Tree Papers",
    "stack": "Python, Cart, Catboost, Classification Model, Classification Trees, Classifier, Decision Tree, Decision Tree Classifier, Decision Tree Learning, Decision Tree Model, Ensemble Learning, Gradient Boosting, Gradient Boosting Machine, Lightgbm, Machine Learning, Machine Learning Research, Random Forest, Regression Tree, Statistical Learning, Tree Ensemble, Xgboost",
    "displayStack": "Python · Cart · Catboost · Classification Model · Classification Trees · Classifier · Decision Tree · Decision Tree Classifier · Decision Tree Learning · Decision Tree Model · Ensemble Learning · Gradient Boosting · Gradient Boosting Machine · Lightgbm · Machine Learning · Machine Learning Research · Random Forest · Regression Tree · Statistical Learning · Tree Ensemble · Xgboost",
    "link": "https://github.com/benedekrozemberczki/awesome-decision-tree-papers",
    "linkLabel": "benedekrozemberczki/awesome-decision-tree-papers",
    "blurb": "A collection of research papers on decision, classification and regression trees with implementations.",
    "outcome": "A collection of research papers on decision, classification and regression trees with implementations.",
    "displayOutcome": "A collection of research papers on decision, classification and regression trees with implementations.",
    "challenge": "A collection of research papers on decision, classification and regression trees with implementations.",
    "bullets": [
      "Starred on GitHub · Primary language: Python.",
      "Topics: cart, catboost, classification-model, classification-trees, classifier, decision-tree, decision-tree-classifier, decision-tree-learning, decision-tree-model, ensemble-learning, gradient-boosting, gradient-boosting-machine, lightgbm, machine-learning, machine-learning-research, random-forest, regression-tree, statistical-learning, tree-ensemble, xgboost."
    ],
    "skills": [
      "Python",
      "Cart",
      "Catboost",
      "Classification Model",
      "Classification Trees",
      "Classifier",
      "Decision Tree",
      "Decision Tree Classifier",
      "Decision Tree Learning",
      "Decision Tree Model",
      "Ensemble Learning",
      "Gradient Boosting",
      "Gradient Boosting Machine",
      "Lightgbm",
      "Machine Learning",
      "Machine Learning Research",
      "Random Forest",
      "Regression Tree",
      "Statistical Learning",
      "Tree Ensemble",
      "Xgboost"
    ]
  }
];

export const starredSkills: string[] = [
  "Ai",
  "Ai Agents",
  "Antigravity",
  "Ast",
  "Authorization",
  "Axum",
  "Bootstrap5",
  "Cart",
  "Catboost",
  "Cedar",
  "Classification Model",
  "Classification Trees",
  "Classifier",
  "Claude Code",
  "Claude Desktop",
  "Claude Mobile",
  "Code Analysis",
  "Code Search",
  "Codegen",
  "Codex",
  "Codex Cli",
  "Coding Assistant",
  "Community",
  "CSS",
  "Css3",
  "Cursor",
  "Datavisualization",
  "Decision Tree",
  "Decision Tree Classifier",
  "Decision Tree Learning",
  "Decision Tree Model",
  "Developer Tools",
  "Dockerfile",
  "Drag And Drop",
  "EJS",
  "Ensemble Learning",
  "Frontend",
  "Gatsby",
  "Gemini",
  "Generator",
  "Github",
  "Globe",
  "Go",
  "Go Template",
  "Gpt 4",
  "Gradient Boosting",
  "Gradient Boosting Machine",
  "Graphrag",
  "Hacktoberfest",
  "Hacktoberfest Accepted",
  "Hacktoberfest2022",
  "HTML",
  "Java",
  "JavaScript",
  "Jupyter Notebook",
  "Knowledge Graph",
  "Layout Engine",
  "Learn",
  "Leiden",
  "Lightgbm",
  "Llm",
  "Localhost",
  "Machine Learning",
  "Machine Learning Research",
  "Makefile",
  "Mako",
  "Markdown",
  "Mcp",
  "Microservices",
  "Next.js",
  "Opa",
  "Opal",
  "Open Policy Agent",
  "Openclaw",
  "Openfga",
  "PHP",
  "PLpgSQL",
  "Policy",
  "Policy As Code",
  "Process Manager",
  "Pubsub",
  "Python",
  "Rag",
  "Random Forest",
  "React",
  "Readme",
  "Realtime",
  "Regression Tree",
  "Research Project",
  "Resizable Panels",
  "Rust",
  "SCSS",
  "Shell",
  "Skills",
  "Smarty",
  "Statistical Learning",
  "Student Vscode",
  "Supabase",
  "Tailwind CSS",
  "Threejs",
  "Tree Ensemble",
  "Tree Sitter",
  "TypeScript",
  "Ui Components",
  "Ui Engineering",
  "Ux Design",
  "Webgl",
  "Websocket",
  "Xgboost"
];
