// This file is generated by scripts/sync-starred-repositories.mjs.
// Do not edit manually.

export type GeneratedProject = {
  name: string;
  displayName: string;
  stack: string;
  displayStack: string;
  link: string;
  linkLabel: string;
  blurb: string;
  outcome: string;
  displayOutcome: string;
  challenge: string;
  bullets: string[];
  skills: string[];
};

export const generatedProjects: GeneratedProject[] = [
  {
    "name": "ArkaPrabhaChowdhury/Unigrade",
    "displayName": "Unigrade",
    "stack": "HTML, CSS, JavaScript, Bootstrap5, Css3",
    "displayStack": "HTML · CSS · JavaScript · Bootstrap5 · Css3",
    "link": "https://github.com/ArkaPrabhaChowdhury/Unigrade",
    "linkLabel": "ArkaPrabhaChowdhury/Unigrade",
    "blurb": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "outcome": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "displayOutcome": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "challenge": "A one-stop solution for all college students. Teachers can upload materials, students can interact with each other and with their mentors, compete using quizzes, get career guidance and much more!",
    "bullets": [
      "Starred on GitHub · Primary language: HTML.",
      "Topics: bootstrap5, css3."
    ],
    "skills": [
      "HTML",
      "CSS",
      "JavaScript",
      "Bootstrap5",
      "Css3"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/Diabetes_Prediction",
    "displayName": "Diabetes Prediction",
    "stack": "Jupyter Notebook",
    "displayStack": "Jupyter Notebook",
    "link": "https://github.com/ArkaPrabhaChowdhury/Diabetes_Prediction",
    "linkLabel": "ArkaPrabhaChowdhury/Diabetes_Prediction",
    "blurb": "Optimal Classification Algorithm for predicting diabetes",
    "outcome": "Optimal Classification Algorithm for predicting diabetes",
    "displayOutcome": "Optimal Classification Algorithm for predicting diabetes",
    "challenge": "Optimal Classification Algorithm for predicting diabetes",
    "bullets": [
      "Starred on GitHub · Primary language: Jupyter Notebook."
    ],
    "skills": [
      "Jupyter Notebook"
    ]
  },
  {
    "name": "ArkaPrabhaChowdhury/ChatbotAPP",
    "displayName": "ChatbotAPP",
    "stack": "Java",
    "displayStack": "Java",
    "link": "https://github.com/ArkaPrabhaChowdhury/ChatbotAPP",
    "linkLabel": "ArkaPrabhaChowdhury/ChatbotAPP",
    "blurb": "A project built and maintained on GitHub.",
    "outcome": "A project built and maintained on GitHub.",
    "displayOutcome": "A project built and maintained on GitHub.",
    "challenge": "A project built and maintained on GitHub.",
    "bullets": [
      "Starred on GitHub · Primary language: Java."
    ],
    "skills": [
      "Java"
    ]
  }
];

export const starredSkills: string[] = [
  "Bootstrap5",
  "CSS",
  "Css3",
  "HTML",
  "Java",
  "JavaScript",
  "Jupyter Notebook"
];
